[theme]
base="dark"
primaryColor="#4da3ff"
backgroundColor="#0b0f14"
secondaryBackgroundColor="#121821"
textColor="#e7eef7"

[client]
toolbarMode = "viewer"  # hides the hamburger help bar for a cleaner look
